### ISSUE TITLE
Crash bizarre zeroconf

### ISSUE THREAD

**Issue by diffty** [MrFrangipane/osc-artnet-daemon#3]
J'ai ce crash que j'avais déjà eu au 211 et je sais pas trop pourquoi et j'ai pas trop de repro mais voilà je le dépose là pour la postérité

```
(.venv) diffty@BebookPro 2024_07_Frangilight % python -m oscartnetdaemon
INFO:oscartnetdaemon.api:Configuration loaded from command line arguments Configuration(is_verbose=False, artnet_target_nodes=['127.0.0.1'], artnet_universe=1, midi_in_port=' ', midi_out_port='OSCArtnetLoopback 1', osc_server_address='0.0.0.0', osc_server_port=8080)
INFO:oscartnetfixtures.components.api:Reloading fixtures and patterns definitions
INFO:oscartnetdaemon.components.osc.server:Starting OSC server (host=0.0.0.0, port=8080)
INFO:oscartnetdaemon.components.midi_tempo:MIDI service starting (in=' ' out='OSCArtnetLoopback 1')
PING 127.0.0.1 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.115 ms

--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.115/0.115/0.115/0.000 ms
INFO:oscartnetdaemon.components.artnet_server:ArtnetServer started 127.0.0.1 for universe 1
INFO:oscartnetdaemon.components.fixtures_updater.fixtures_updater:Starting Fixture Updater
WARNING:oscartnetdaemon.components.midi_tempo:MIDI out port 'OSCArtnetLoopback 1' not found
WARNING:oscartnetdaemon.components.midi_tempo:Falling back to fixed 120 bpm tempo
INFO:oscartnetdaemon.components.discovery.discovery:Starting Discovery service
INFO:oscartnetdaemon.components.osc.message_sender:Registering client iPad de DiFFtY (192.168.20.237)
INFO:oscartnetdaemon.components.osc.message_sender:Registering client iPad de DiFFtY (2) (192.168.20.237)
WARNING:oscartnetdaemon.components.osc.message_handler:not enough values to unpack (expected 3, got 2)
Exception in thread zeroconf-ServiceBrowser-_osc._udp-1725585:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "src/zeroconf/_services/browser.py", line 783, in zeroconf._services.browser.ServiceBrowser.run
  File "src/zeroconf/_services/browser.py", line 702, in zeroconf._services.browser._ServiceBrowserBase._fire_service_state_changed_event
  File "src/zeroconf/_services/browser.py", line 712, in zeroconf._services.browser._ServiceBrowserBase._fire_service_state_changed_event
  File "src/zeroconf/_services/__init__.py", line 56, in zeroconf._services.Signal.fire
  File "/Users/diffty/Documents/_Projets/Events/2024_07_Frangilight/osc-artnet-daemon/oscartnetdaemon/components/discovery/discovery.py", line 60, in _on_service_change
    id=info.properties[b'IID'],
       ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: b'IID'
```

**Comment by MrFrangipane** [comment]
Merci pour ce ticket :)

Il me semble que j'avais corrigé ce bug

Je crois que ca vient du fait que résolume utilise aussi zero conf pour s'annoncer en tant que noeud OSC, mais ne met pas les memes éléments que Touch dans son service info

**Comment by MrFrangipane** [comment]
Faudra que je re teste :)

**Comment by diffty** [comment]
ah oui c'est très possible, quand j'avais eu ce souci c'est quand j'avais aussi Resolume qui tournait sur mon Macbook sur le même réseau !
